'use client';
import { useEffect, useActionState } from 'react';
import { useFormStatus } from 'react-dom';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useAppContext } from '@/context/app-context';
import { handleAdImageGeneration } from '@/app/actions';
import { GalleryHorizontal, Sparkles } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Skeleton } from '@/components/ui/skeleton';

const initialState = {
  message: '',
  errors: {},
  data: null,
};

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" aria-disabled={pending} disabled={pending} className="w-full bg-accent hover:bg-accent/90 text-accent-foreground">
      {pending ? (
        <>
          <Sparkles className="mr-2 animate-pulse" /> Generating...
        </>
      ) : (
        'Generate Image'
      )}
    </Button>
  );
}

export default function MarketingSuitePage() {
  const { setPageTitle } = useAppContext();
  const [state, formAction] = useActionState(handleAdImageGeneration, initialState);
  const { pending } = useFormStatus();

  useEffect(() => {
    setPageTitle('AI Marketing Suite');
  }, [setPageTitle]);

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="font-headline text-2xl flex items-center gap-2">
            <GalleryHorizontal className="text-primary" />
            AI-Powered Marketing Images
          </CardTitle>
          <CardDescription>
            Describe your crop, and our AI will generate a beautiful, professional marketing image for your listing.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form action={formAction} className="space-y-4">
            <div className="space-y-2">
              <label htmlFor="description" className="font-medium">Crop Description</label>
              <Input
                id="description"
                name="description"
                placeholder="e.g., 'Freshly harvested Roma tomatoes, bright red and juicy'"
                className="text-base"
              />
              {state.errors?.description && (
                <p className="text-sm font-medium text-destructive">{state.errors.description[0]}</p>
              )}
            </div>
            <SubmitButton />
          </form>
        </CardContent>
      </Card>

      {pending && (
        <Card>
          <CardHeader>
            <CardTitle>Generating Your Image...</CardTitle>
            <CardDescription>This may take a moment. Please wait.</CardDescription>
          </CardHeader>
          <CardContent>
            <Skeleton className="w-full aspect-video rounded-md" />
          </CardContent>
        </Card>
      )}

      {state.message && !state.data && state.message !== 'Invalid form data.' && (
         <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{state.message}</AlertDescription>
        </Alert>
      )}

      {state.data && (
        <Card className="shadow-md animate-in fade-in-50">
          <CardHeader>
            <CardTitle className="font-headline text-2xl">Generated Image</CardTitle>
            <CardDescription>Here is the marketing image generated by our AI. You can right-click to save it.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="relative w-full aspect-video rounded-md overflow-hidden border">
              <Image src={state.data.imageUrl} alt="AI generated marketing image" fill className="object-cover" />
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
